### ISSUE TITLE
Doesn't generate data if only default class constructor is available

### ISSUE THREAD

**Issue by egidijusk** [Vacxe/Konveyor#19]
Take the following class for example.

```java
public class Point {

    private double x, y;

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }
}
```

If you generate an object `Point randomPoint = KonveyorKt.randomBuild(Point.class)` the `x` and `y` values are always `0.0`. Is there a way to generate a random object without adding a constructor for `x` and `y`? This is a serious drawback of this library.

**Comment by Vacxe** [comment]
@egidijusk sorry for late response. Just a bit busy for this time. Will check this issue ASAP

**Comment by Vacxe** [comment]
@egidijusk now all generation work through constructors. F.E. if u can add 

```public Point(double x, double y) {
this.x = x;
this.y = y;
} ```

Does it work for you or u wanna have additional functionality?

**Comment by egidijusk** [comment]
@Vacxe I know that it works if you add a constructor for `x` and `y`. What I'm saying is it would be nice if you shouldn't have to. The library could make use of java reflection. For example, [this](https://github.com/j-easy/easy-random) library does. In practice there are many classes where you would set variable values using setters and not constructors.

**Comment by Vacxe** [comment]
@egidijusk The main target of this library is a mocking object trough constructors. If the object contains the inner variable or setters that's additional logic and should cover buy user. 

Usage of reflection for settings everything with excluded variants looks strange for me.
